# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
compiler: gcc
r_check_args: --as-cran
sudo: required

before_install:
# https://raw.githubusercontent.com/craigcitro/r-travis/master/sample.travis.yml
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
# C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  ## For installing all CRAN dependencies using rpack's DESCRIPTION
  - ./travis-tool.sh install_deps
  
r_github_packages:
- bozenne/butils.base
- tagteam/Publish

after_success:
- Rscript -e 'library(covr);coveralls()'

after_failure:
- ./travis-tool.sh dump_logs