# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
compiler: gcc
r_check_args: --as-cran
sudo: required

repos:
  CRAN: https://cloud.r-project.org
  
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
- sudo apt-get -qq install g++-4.8

r_github_packages:
- tagteam/Publish

after_success:
- Rscript -e 'library(covr);coveralls()'

after_failure:
- ./travis-tool.sh dump_logs