# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Use the R testing scheme
language: R
cache: packages
compiler: gcc
dist: precise
r_check_args: --as-cran
sudo: false

CRAN: http://cran.rstudio.com

r_github_packages:
- tagteam/Publish
- tagteam/riskRegression
 
before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # R
  - R -e 'devtools::install_deps(dep = T)'

after_success:
- Rscript -e 'library(covr);coveralls()'

after_failure:
- ./travis-tool.sh dump_logs