# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_check_args: --as-cran
cache: packages

r_github_packages:
- bozenne/butils.base

after_success:
- Rscript -e 'library(covr);coveralls()'

after_failure:
- ./travis-tool.sh dump_logs