# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
compiler: gcc
r_check_args: --as-cran
sudo: required

repos:
  CRAN: https://cloud.r-project.org
  
r_github_packages:
- tagteam/Publish

after_success:
- Rscript -e 'library(covr);coveralls()'

after_failure:
- ./travis-tool.sh dump_logs