# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
compiler: gcc
r_check_args: --as-cran
sudo: required


before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

r_github_packages:
- bozenne/butils.base
- tagteam/Publish

after_success:
- Rscript -e 'library(covr);coveralls()'

after_failure:
- ./travis-tool.sh dump_logs