# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_check_args: --as-cran
sudo: required

cache: packages

repos:
  CRAN: http://cran.rstudio.com 
 
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-6
 - sudo apt-get install -qq gfortran-6
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6  90
 - sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-6  90 
 - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 90

r_github_packages:
- tagteam/Publish
- tagteam/riskRegression

after_success:
- Rscript -e 'library(covr);coveralls()'

#####
## This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid, and setgid executables.
## If you require sudo, add 'sudo: required' to your .travis.yml
## >>> this is why I use "sudo: required"

#####
## * installing *source* package ‘RcppArmadillo’ ...
## configure: WARNING: Only g++ version 4.7.2 or greater can be used with RcppArmadillo.
## configure: error: Please use a different compiler.
## ERROR: configuration failed for package ‘RcppArmadillo’
## >>> this is why I have added the lines C++14 as advised here:
##     https://gist.github.com/cotsog/3ce84675af0d74438d91 

#####
## BUT then I got 
##  * checking package dependencies ... ERROR
##
## Packages required but not available:
##
##  ‘data.table’ ‘ggplot2’ ‘corrplot’ ‘doParallel’ ‘foreach’ ‘gdata’
##
##  ‘merTools’ ‘proftools’ ‘profvis’ ‘riskRegression’
##
## Packages suggested but not available:
##
##  ‘AICcmodavg’ ‘heplots’ ‘lava’ ‘lme4’ ‘Publish’ ‘testthat’
## This is normal since I have overwritten the install (see https://github.com/travis-ci/travis-ci/issues/5650)

#####
## So I tried to put all the commands in before_install
## It seemed to work since I got "checking whether g++ version is sufficient... (6.3.0) yes"
## But I also got
## g++ -shared -L/home/travis/R-bin/lib -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -fopenmp -L/home/travis/R-bin/lib/R/lib -lRlapack -L/home/travis/R-bin/lib/R/lib -lRblas -lgfortran -lm -lquadmath
## /usr/bin/ld: cannot find -lgfortran
## collect2: error: ld returned 1 exit status
## make: *** [RcppArmadillo.so] Error 1
## ERROR: compilation failed for package ‘RcppArmadillo’
## Similar issue was reported here: https://github.com/igraph/igraph/issues/979

#####
## According to https://stackoverflow.com/questions/42150845/usr-bin-ld-cannot-find-lgfortran-when-installing-rcpparmadillo-in-r
## this is because "Gfortran is a part of the GCC package. It is an optional part, but in this case you really want it to be included."
## So I am trying to find how to install both gcc and gfortran at the same time
## It works when I ask for compatible versions of gcc and gfortran