# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Apply cumsum in each column 
#'
#' @description Fast computation of apply(x,2,cumsum)
#' @param x A matrix.
#' @return A matrix of same size as x.
#' @author Thomas Alexander Gerds <tag@@biostat.ku.dk>
#' @examples
#' x <- matrix(1:8,ncol=2)
#' colCumSum(x)
#' @export
colCumSum <- function(x) {
    .Call('butils_colCumSum', PACKAGE = 'butils', x)
}

hello0 <- function() {
    invisible(.Call('butils_hello0', PACKAGE = 'butils'))
}

hello1 <- function(A) {
    .Call('butils_hello1', PACKAGE = 'butils', A)
}

hello2 <- function(A, B) {
    .Call('butils_hello2', PACKAGE = 'butils', A, B)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('butils_RcppExport_registerCCallable', PACKAGE = 'butils')
})
